apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: online-shop-demo
data:
  REDIS_HOST: host.docker.internal
  REDIS_PORT: "6379"
  BOOK_SERVICE_URL: book-service:8080
  ORDER_SERVICE_URL: order-service:8080
