apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
  namespace: online-shop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ysavchen/api-gateway:1.0.0
          imagePullPolicy: Always  # for dev purposes
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
          envFrom:
            - configMapRef:
                name: api-gateway-config
