apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: online-shop-demo
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
