services:

  ### Storage ###
  postgres:
    image: postgres:17.0-alpine
    container_name: postgres
    environment:
      PGTZ: Europe/Moscow
      POSTGRES_DB: "online_shop_demo"
      POSTGRES_USER: "app_user"
      POSTGRES_PASSWORD: "app_password"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - storage

  redis:
    image: redis/redis-stack:7.4.0-v1
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - storage


  ### Test ###
  wiremock:
    image: wiremock/wiremock:3.9.2-alpine
    container_name: wiremock
    profiles: [ "test" ]
    ports:
      - "8090:8080"   # book-service port
    volumes:
      - ./wiremock:/home/wiremock/mappings
    networks:
      - test


  ### Messaging ###
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: "qel01sxrQlyFTkcVYzAMZp"
    networks:
      - messaging

  init-kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: init-kafka
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --topic order-service.domain --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --topic delivery-service.request --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --topic delivery-service.reply --replication-factor 1 --partitions 1
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "
    networks:
      - messaging

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "9095:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - messaging


  ### Observability ###
  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    networks:
      - observability

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: node-exporter
    profiles: [ "node-exporter" ]
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    volumes:
      - "/:/host:ro,rslave"

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    depends_on:
      - prometheus
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    networks:
      - observability

  smtp4dev:
    image: rnwood/smtp4dev:3.6.1
    container_name: smtp4dev
    depends_on:
      - alertmanager
    ports:
      - "5000:80"
      - "25:25"
    networks:
      - observability

  ## Grafana stack ##
  loki:
    image: grafana/loki:3.2.1
    container_name: loki
    environment:
      TZ: ${SYSTEM_TIMEZONE:-Europe/Moscow}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    networks:
      - observability

  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/var/tempo
    ports:
      - "3200:3200"    # tempo
      - "4318:4318"    # otlp http
      - "9411:9411"    # zipkin
    networks:
      - observability

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    user: "104"
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_INSTALL_PLUGINS: >
        https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app,
        https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana
    networks:
      - observability

networks:
  storage:
  test:
  messaging:
  observability: