replicaCount: 1

image:
  repository: ysavchen/api-gateway
  pullPolicy: Always # for dev purposes
  ports:
    containerPort: 8080

namespace: online-shop-demo

podLabels:
  app: api-gateway

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 5
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 5

configmap:
  data:
    redisHost: host.docker.internal
    redisPort: 6379
    bookServiceUrl: book-service:8080
    orderServiceUrl: order-service:8080
