replicaCount: 1

image:
  repository: ysavchen/api-gateway
  pullPolicy: Always

namespace: online-shop-demo

podLabels:
  app: api-gateway

service:
  type: NodePort
  port: 8080

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  failureThreshold: 3
  initialDelaySeconds: 5
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  failureThreshold: 3
  initialDelaySeconds: 5
