apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
  namespace: online-shop-demo
data:
  serverPort: "8080"
  postgresUrl: jdbc:postgresql://host.docker.internal:5432/online_shop_demo?currentSchema=delivery_service
