apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  labels:
    app: delivery-service
  namespace: online-shop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: ysavchen/delivery-service:1.0.0
          imagePullPolicy: Always  # for dev purposes
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 150
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 150
          envFrom:
            - configMapRef:
                name: delivery-service-config
            - secretRef:
                name: postgres-secret
