{
 "title": "RED Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Service", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_requests_seconds_count{status!~\"2..|3..\",application=\"$application\"}[1m]))\r\n/\r\nsum by (job) (rate(http_server_requests_seconds_count{application=\"$application\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_requests_seconds_bucket{application=\"$application\"}[1m])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_server_requests_seconds_bucket{application=\"$application\"}[1m])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{application=\"$application\"}[1m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_requests_seconds_bucket{application=\"$application\"}[1m])))",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}