version: "3.9"

services:
  book_service_postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "book_service_db"
      POSTGRES_USER: "book_service_user"
      POSTGRES_PASSWORD: "book_service_password"
    ports:
      - "5432:5432"
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging

  logstash:
    image: logstash:8.5.3
    container_name: logstash
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    depends_on:
      - elasticsearch
    volumes:
      - ./infra/logstash:/etc/grafana
    networks:
      - logging

  kibana:
    image: kibana:8.5.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: "kibana_password"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - logging

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.4.1
    user: "104"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana:/etc/grafana
    networks:
      - monitoring

networks:
  backend:
  logging:
  monitoring:
