spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: book-service
          uri: http://localhost:8090
          predicates:
            - Path=/book-service/**
          filters:
            - RewritePath=/book-service/(?<path>.*), /$\{path}

server:
  port: 8080

management:
  endpoints:
    web.exposure.include: health,gateway,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG