spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      actuator:
        verbose.enabled: true
      routes:
        - id: book-service
          uri: http://localhost:8090
          predicates:
            - Path=/book-service/**
          filters:
            - RewritePath=/book-service/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 2
                  burstCapacity: 2

        - id: order-service
          uri: http://localhost:8091
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 2
                  burstCapacity: 2

server:
  port: 8080

management:
  health:
    redis.enabled: true
  endpoint:
    gateway.enabled: true
  endpoints:
    web.exposure.include: health,gateway,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG