spring:
  application:
    name: api-gateway
    org: online-shop-demo
  cloud:
    gateway:
      actuator:
        verbose.enabled: true
      routes:
        - id: book-service
          uri: ${BOOK_SERVICE_URL:http://localhost:8090}
          predicates:
            - Path=/api-gateway/api/v1/books/**
          filters:
            - RewritePath=/api-gateway/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 15 # допустимое количество запросов в секунду при нормальной нагрузке
                  burstCapacity: 15 # максимальное количество запросов в секунду в случае всплеска нагрузки
                  requestedTokens: 1 # вес запроса в виде количества токенов в корзине

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8091}
          predicates:
            - Path=/api-gateway/api/v1/orders/**
          filters:
            - RewritePath=/api-gateway/(?<path>.*), /$\{path}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 15
                  burstCapacity: 15

server:
  port: 8080
  shutdown: graceful

management:
  health:
    probes.enabled: true
  endpoint:
    gateway.enabled: true
  endpoints:
    web.exposure.include: health,gateway,metrics,prometheus
  observations:
    key-values.org: ${spring.application.org}
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG