version: "3.9"

services:
  postgres:
    image: postgres:14.2
    container_name: app-db
    environment:
      POSTGRES_DB: "app_db"
      POSTGRES_USER: "app_user"
      POSTGRES_PASSWORD: "app_password"
    ports:
      - "5432:5432"
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging

  kibana:
    image: kibana:8.5.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: "kibana_password"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - logging

  prometheus:
    image: prom/prometheus:v2.40.5
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana:/etc/grafana
    networks:
      - monitoring

networks:
  backend:
  logging:
  monitoring:
