apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
  namespace: online-shop-demo
data:
  SERVER_PORT: "8080"
  POSTGRES_URL: jdbc:postgresql://host.docker.internal:5432/online_shop_demo?currentSchema=book_service
