apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
  namespace: online-shop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: ysavchen/book-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always # for dev purposes
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 5
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: serverPort
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: postgresUrl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
