apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: online-shop-demo
  labels:
    app: book-service
spec:
  selector:
    app: book-service
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
