apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: online-shop-demo
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/online_shop_demo?currentSchema=order_service
