spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop_demo?currentSchema=book_service
    username: app_user
    password: app_password
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master.yaml

info:
  application:
    name: ${spring.application.name}
    version: 1.0

server:
  port: 8090

management:
  info.env.enabled: true
  endpoints:
    web.exposure.include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus.enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true