spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop_demo?currentSchema=book_service
    username: app_user
    password: app_password
  data.web:
    pageable:
      one-indexed-parameters: true
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master.yaml

server:
  port: 8090
  shutdown: graceful

management:
  health:
    probes.enabled: true
  endpoints:
    web.exposure.include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true