spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/book_service_db
    username: book_service_user
    password: book_service_password
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master.yaml

info:
  application:
    name: ${spring.application.name}
    version: 1.0

management:
  info.env.enabled: true
  endpoint:
    health.show-details: always
  endpoints:
    web.exposure.include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus.enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true