apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-shop-ingress
  namespace: online-shop-demo
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api-gateway
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /api/*/books
            pathType: Prefix
            backend:
              service:
                name: book-service
                port:
                  number: 8080
          - path: /api/*/orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8080
