spring:
  application:
    name: order-service
  threads:
    virtual.enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop_demo?currentSchema=order_service
    username: app_user
    password: app_password
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master.yaml

server:
  port: 8091

management:
  health:
    probes.enabled: true
  endpoints:
    web.exposure.include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true