apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  redisHost: {{ .Values.configmap.data.redisHost }}
  redisPort: {{ .Values.configmap.data.redisPort | quote }}
  bookServiceUrl: {{ .Values.configmap.data.bookServiceUrl }}
  orderServiceUrl: {{ .Values.configmap.data.orderServiceUrl }}