apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: {{ .Values.configmap.data.redisHost }}
  REDIS_PORT: {{ .Values.configmap.data.redisPort | quote }}
  BOOK_SERVICE_URL: {{ .Values.configmap.data.bookServiceUrl }}
  ORDER_SERVICE_URL: {{ .Values.configmap.data.orderServiceUrl }}