global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'book-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8090' ]
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8091' ]
