spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop_demo?currentSchema=delivery_service
    username: app_user
    password: app_password
    hikari:
      connection-timeout: 3000 # default is 30000
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master.yaml

server:
  port: 8092
  shutdown: graceful

management:
  health:
    disk-space.enabled: false
  endpoint:
    health:
      show-components: always
      probes.enabled: true
      group:
        readiness:
          include:
            - readinessState
            - db
  endpoints:
    web.exposure.include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true