name: Build api-gateway

on:
  push:
    branches: [ main ]
    paths:
      - '*/api-gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build api-gateway
        run: ./gradlew build -p ./04-services/api-gateway

  dependency-submissions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
