name: Build book-service

on:
  push:
    branches: [ main ]
    paths:
      - '*/book-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build online-shop-model
        run: ./gradlew publishToMavenLocal -p ./05-libraries/online-shop-model

      - name: Build adapters
        run: ./gradlew publishToMavenLocal -p ./05-libraries/adapters

      - name: Build book-service
        run: ./gradlew build -p ./04-services/book-service

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          build-root-directory: ./04-services/book-service
