name: Build book-service

on:
  push:
    branches: [ main ]
    paths:
      - '*/book-service/**'

jobs:
  book-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"

      - name: Build adapters
        run: cd ./05-libraries/adapters && gradle publishToMavenLocal

      - name: Build book-service
        run: cd ./04-services/book-service && gradle build
