# This workflow builds book-service with Gradle

name: Build book-service

on:
  push:
    branches: [ main ]
    paths:
      - 'book-service/**'

jobs:
  book-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build with Gradle
        run: cd ./book-service && chmod +x gradlew && ./gradlew build --no-daemon
