# This workflow builds services with Gradle

name: Build services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build with Gradle
        run: cd ./api-gateway && ./gradlew build --no-daemon
