# This workflow builds online-shop-model with Gradle

name: Build online-shop-model

on:
  push:
    branches: [ main ]
    paths:
      - '*/online-shop-model/**'

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build with Gradle
        run: cd ./05-libraries/online-shop-model && chmod +x gradlew && ./gradlew build --no-daemon