name: Build order-service

on:
  push:
    branches: [ main ]
    paths:
      - '*/order-service/**'

jobs:
  order-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"

      - name: Build online-shop-model
        run: gradle publishToMavenLocal -p ./05-libraries/online-shop-model

      - name: Build adapters
        run: gradle publishToMavenLocal -p ./05-libraries/adapters

      - name: Build order-service
        run: gradle build -p ./04-services/order-service
