spring:
  application:
    name: order-service
    org: online-shop-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop_demo?currentSchema=order_service
    username: app_user
    password: app_password
    hikari:
      connection-timeout: 3000 # default is 30000
  data.web:
    pageable:
      one-indexed-parameters: true # config doesn't work, bug in Spring
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 10
  liquibase:
    change-log: classpath:liquibase/master.yaml

application:
  timezone: Europe/Moscow # made timezone configurable for dev purposes

server:
  port: 8091

management:
  health:
    disk-space.enabled: false
  endpoint:
    health:
      show-components: always
      probes.enabled: true
      group:
        readiness:
          include:
            - readinessState
            - db
  endpoints:
    web.exposure.include: health,metrics,prometheus
  observations:
    key-values.org: ${spring.application.org}
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      # Publish a cumulative histogram with buckets defined by your service-level objectives
      slo.http.server.requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s, 2s, 5s
  tracing:
    sampling:
      probability: 1.0